CREATE TABLE IF NOT EXISTS campaign_images (
  id SERIAL PRIMARY KEY,
  campaign_id INT NOT NULL,
  is_primary INT NOT NULL DEFAULT 0,
  file_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE
);